#pragma shader_stage(compute)

layout(local_size_x = 4, local_size_y = 4) in;
layout(binding = 0, rgba32f) restrict writeonly uniform image2D o_Image;

layout(binding = 1) uniform sampler2D screenTexture;
layout(binding = 2) uniform sampler2D bloomTexture;

void main() { 
  vec2 imgSize = vec2(imageSize(o_Image));
  ivec2 invocID = ivec2(gl_GlobalInvocationID);
  vec2 texCoords = vec2(float(invocID.x) / imgSize.x, float(invocID.y) / imgSize.y);
  texCoords += (1.f / imgSize) * 0.5f;

  vec3 result = texture(screenTexture, texCoords).rgb + texture(bloomTexture, texCoords).rgb;
  
  // HDR tonemapping
  result = result / (result + 1.f);
  // gamma correct
  result = pow(result, vec3(1.f / 2.2f));

  imageStore(o_Image, invocID, vec4(result, 1.f));
}