#version 450

layout(local_size_x = 4, local_size_y = 4) in;
layout(binding = 0, rgba32f) restrict writeonly uniform image2D o_Image;

struct Vertex {
	vec2 texCoord;
	vec3 position;
};

struct Light {
	vec3 vector;
	uint color;
};

float rtLerp(const in vec3 uvw, const in float a, const in float b, const in float c) { return uvw.x * a + uvw.y * b + uvw.z * c; }
vec2 rtLerp(const in vec3 uvw, const in vec2 a, const in vec2 b, const in vec2 c) { return uvw.x * a + uvw.y * b + uvw.z * c; }
vec3 rtLerp(const in vec3 uvw, const in vec3 a, const in vec3 b, const in vec3 c) { return uvw.x * a + uvw.y * b + uvw.z * c; }
vec4 rtLerp(const in vec3 uvw, const in vec4 a, const in vec4 b, const in vec4 c) { return uvw.x * a + uvw.y * b + uvw.z * c; }

layout (std140, binding = 0) uniform SceneData
{
	vec3 lower_left_corner;
	vec3 horizontal;
	vec3 vertical;
	vec3 cameraPos;
    uint IndexCount;
    uint numLights;
	uint maxBounces;
};

layout (std140, binding = 1) uniform Lighting { Light lights[1]; };
layout (std430, binding = 2) readonly buffer VertexData { Vertex vertices[1]; };
layout (std430, binding = 3) readonly buffer IndexData { uint indices[1]; };

layout(binding = 1) uniform sampler2D u_Albedo;
layout(binding = 2) uniform sampler2D u_MaterialInfo;

vec3 Intersection(const in vec3 rayOrigin, const in vec3 rayDirection, const in uint i) {
	vec3 a = vertices[indices[i]].position;
	vec3 b = vertices[indices[i + 1]].position;
	vec3 c = vertices[indices[i + 2]].position;
	vec3 e1 = b - a;
	vec3 e2 = c - a;
    vec3 crossRDE2 = cross(rayDirection, e2);
    float dotE1CrossRDE2 = 1.f / dot(e1, crossRDE2);
	vec3 rOa = rayOrigin - a;
	vec3 crossROAE1 = cross(rOa, e1);
	vec2 uv;
	uv.x = dot(rOa, crossRDE2) * dotE1CrossRDE2;
	uv.y = dot(rayDirection, crossROAE1 * dotE1CrossRDE2);

	float t = dot(e2, crossROAE1) * dotE1CrossRDE2;
		if (!(t <= 0.f || uv.x < 0.f || uv.x > 1.f || uv.y < 0.f || uv.x + uv.y > 1.f))
			return vec3(t, uv);
		else 
			return vec3(0.f, uv);	
}

#define MAX_STEPS 100
#define SURF_DIST .01

const float kInfinity = 3.402823466e+38F;
const float MAX_DIST = 3.402823466e+38F;

float dot2( in vec3 v ) { return dot(v,v); }

float udTriangle( in vec3 v1, in vec3 v2, in vec3 v3, in vec3 p )
{
    vec3 v21 = v2 - v1; vec3 p1 = p - v1;
    vec3 v32 = v3 - v2; vec3 p2 = p - v2;
    vec3 v13 = v1 - v3; vec3 p3 = p - v3;
    vec3 nor = cross( v21, v13 );

    return sqrt( (sign(dot(cross(v21,nor),p1)) + 
                  sign(dot(cross(v32,nor),p2)) + 
                  sign(dot(cross(v13,nor),p3))<2.0) 
                  ?
                  min( min( 
                  dot2(v21*clamp(dot(v21,p1)/dot2(v21),0.0,1.0)-p1), 
                  dot2(v32*clamp(dot(v32,p2)/dot2(v32),0.0,1.0)-p2) ), 
                  dot2(v13*clamp(dot(v13,p3)/dot2(v13),0.0,1.0)-p3) )
                  :
                  dot(nor,p1)*dot(nor,p1)/dot2(nor) );
}

float GetDist(vec3 p) {    

    float minT = kInfinity;

	for (uint i = 0; i < IndexCount; i += 3) 
		minT = min(minT, udTriangle(vertices[indices[i]].position, vertices[indices[i + 1]].position, vertices[indices[i + 2]].position, p));	
    
    return minT;
}

float GetDistAndData(vec3 p, out uint id) {    

    float minT = kInfinity;

	for (uint i = 0; i < IndexCount; i += 3) {
        float d = udTriangle(vertices[indices[i]].position, vertices[indices[i + 1]].position, vertices[indices[i + 2]].position, p);
        if (d < minT){
		    minT = d;
            id = i;
        }
    }
    
    return minT;
}

float RayMarch(vec3 ro, vec3 rd, out uint id) {
	float dO = 0.f;
    
    for(int i=0; i<MAX_STEPS; i++) {
    	vec3 p = ro + rd*dO;
        float dS = GetDistAndData(p, id);
        dO += dS;
        if(dO>MAX_DIST || dS<SURF_DIST) break;
    }
    
    return dO;
}

vec3 GetNormal(vec3 p) {
	float d = GetDist(p);
    vec2 e = vec2(.01, 0);
    
    vec3 n = d - vec3(
        GetDist(p-e.xyy),
        GetDist(p-e.yxy),
        GetDist(p-e.yyx));
    
    return normalize(n);
}

const float Epsilon = 1.0e-4;
const float bias = 1e-4;

const float PI = 3.14159265358979323846264338327950288f;

float DistributionGGX(const in vec3 N, const in vec3 H, const in float roughness)
{
	float a = roughness * roughness;
	float a2 = a * a;
	float NdotH = max(dot(N, H), 0.f);
	float NdotH2 = NdotH * NdotH;

	float nom = a2;
	float denom = NdotH2 * (a2 - 1.f) + 1.f;
	denom = PI * denom * denom;

	return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySchlickGGX(const in float NdotV, const in float roughness)
{
	float r = roughness + 1.f;
	float k = r * r * 0.125f;

	//float nom = NdotV;
	//float denom = NdotV * (1.f - k) + k;
	//	   nom   / denom
	return NdotV / (NdotV * (1.f - k) + k);
}

vec3 fresnelSchlick(const in float cosTheta, const in vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}
// ----------------------------------------------------------------------------
vec3 fresnelSchlickRoughness(const in float cosTheta, const in vec3 F0, const in float roughness)
{
    return F0 + (max(vec3(1.0 - roughness), F0) - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

/*sky start*/
float hash( const in float n ) { return fract(sin(n)*4378.5453); }

float hash1( vec2 p )
{
    p  = 50.0*fract( p*0.3183099 );
    return fract( p.x*p.y*(p.x+p.y) );
}

float hash1( float n )
{
    return fract( n*17.0*fract( n*0.3183099 ) );
}

const mat3 m3  = mat3( 0.00,  0.80,  0.60,
                      -0.80,  0.36, -0.48,
                      -0.60, -0.48,  0.64 );

vec4 noised( in vec3 x )
{
    vec3 p = floor(x);
    vec3 w = fract(x);
    #if 1
    vec3 u = w*w*w*(w*(w*6.0-15.0)+10.0);
    vec3 du = 30.0*w*w*(w*(w-2.0)+1.0);
    #else
    vec3 u = w*w*(3.0-2.0*w);
    vec3 du = 6.0*w*(1.0-w);
    #endif

    float n = p.x + 317.0*p.y + 157.0*p.z;
    
    float a = hash1(n+0.0);
    float b = hash1(n+1.0);
    float c = hash1(n+317.0);
    float d = hash1(n+318.0);
    float e = hash1(n+157.0);
	float f = hash1(n+158.0);
    float g = hash1(n+474.0);
    float h = hash1(n+475.0);

    float k0 =   a;
    float k1 =   b - a;
    float k2 =   c - a;
    float k3 =   e - a;
    float k4 =   a - b - c + d;
    float k5 =   a - c - e + g;
    float k6 =   a - b - e + f;
    float k7 = - a + b + c - d + e - f - g + h;

    return vec4( -1.0+2.0*(k0 + k1*u.x + k2*u.y + k3*u.z + k4*u.x*u.y + k5*u.y*u.z + k6*u.z*u.x + k7*u.x*u.y*u.z), 
                      2.0* du * vec3( k1 + k4*u.y + k6*u.z + k7*u.y*u.z,
                                      k2 + k5*u.z + k4*u.x + k7*u.z*u.x,
                                      k3 + k6*u.x + k5*u.y + k7*u.x*u.y ) );
}

float noise( in vec3 x )
{
    vec3 p = floor(x);
    vec3 w = fract(x);
    
    vec3 u = w*w*w*(w*(w*6.0-15.0)+10.0);

    float n = p.x + 317.0*p.y + 157.0*p.z;
    
    float a = hash1(n+0.0);
    float b = hash1(n+1.0);
    float c = hash1(n+317.0);
    float d = hash1(n+318.0);
    float e = hash1(n+157.0);
	float f = hash1(n+158.0);
    float g = hash1(n+474.0);
    float h = hash1(n+475.0);

    float k0 =   a;
    float k1 =   b - a;
    float k2 =   c - a;
    float k3 =   e - a;
    float k4 =   a - b - c + d;
    float k5 =   a - c - e + g;
    float k6 =   a - b - e + f;
    float k7 = - a + b + c - d + e - f - g + h;

    return -1.0+2.0*(k0 + k1*u.x + k2*u.y + k3*u.z + k4*u.x*u.y + k5*u.y*u.z + k6*u.z*u.x + k7*u.x*u.y*u.z);
}

vec3 noised( in vec2 x )
{
    vec2 p = floor(x);
    vec2 w = fract(x);
    #if 1
    vec2 u = w*w*w*(w*(w*6.0-15.0)+10.0);
    vec2 du = 30.0*w*w*(w*(w-2.0)+1.0);
    #else
    vec2 u = w*w*(3.0-2.0*w);
    vec2 du = 6.0*w*(1.0-w);
    #endif
    
    float a = hash1(p+vec2(0,0));
    float b = hash1(p+vec2(1,0));
    float c = hash1(p+vec2(0,1));
    float d = hash1(p+vec2(1,1));

    float k0 = a;
    float k1 = b - a;
    float k2 = c - a;
    float k4 = a - b - c + d;

    return vec3( -1.0+2.0*(k0 + k1*u.x + k2*u.y + k4*u.x*u.y), 
                 2.0*du * vec2( k1 + k4*u.y,
                            k2 + k4*u.x ) );
}

vec4 fbmd_8( in vec3 x )
{
    float f = 2.0;
    float s = 0.65;
    float a = 0.0;
    float b = 0.5;
    vec3  d = vec3(0.0);
    mat3  m = mat3(1.0,0.0,0.0,
                   0.0,1.0,0.0,
                   0.0,0.0,1.0);
    for( int i=0; i<8; i++ )
    {
        vec4 n = noised(x);
        a += b*n.x;          // accumulate values		
        if( i<4 )
        d += b*m*n.yzw;      // accumulate derivatives
        b *= s;
        x = f*m3*x;
        m = f*m3*m;
    }
	return vec4( a, d );
}

vec4 cloudsFbm( in vec3 pos , in float iTime)
{
    return fbmd_8(pos*0.0015+vec3(2.0,1.1,1.0)+0.07*vec3(iTime,0.5*iTime,-0.15*iTime));
}

vec4 cloudsMap( in vec3 pos, out float nnd )
{
    float d = abs(pos.y-900.0)-40.0;
    vec3 gra = vec3(0.0,sign(pos.y-900.0),0.0);
    
    vec4 n = cloudsFbm(pos, 0.f);
    d += 400.0*n.x * (0.7+0.3*gra.y);
    
    if( d>0.0 ) return vec4(-d,0.0,0.0,0.0);
    
	d = -d;
    nnd = d;
    d = min(d/100.0,0.25);
    
    //gra += 0.1*n.yzw *  (0.7+0.3*gra.y);
    
    return vec4( d, gra );
}

vec4 renderClouds( in vec3 ro, in vec3 rd, float tmin, float tmax, inout float resT, in vec2 px )
{
    vec4 sum = vec4(0.0);

    // bounding volume!!
    float tl = ( 600.0-ro.y)/rd.y;
    float th = (1200.0-ro.y)/rd.y;
    if( tl>0.0 ) tmin = max( tmin, tl ); else return sum;
    if( th>0.0 ) tmax = min( tmax, th );

    float t = tmin;
    float lastT = -1.0;
    float thickness = 0.0;
    for(int i=0; i<128; i++)
    { 
        vec3  pos = ro + t*rd; 
        float nnd;
        vec4  denGra = cloudsMap( pos, nnd ); 
        float den = denGra.x;
        float dt = max(0.2,0.011*t);
        //dt *= hash1(px+float(i));
        if( den>0.001 ) 
        { 
            float kk;
            cloudsMap( pos+lights[0].vector*70.0, kk );
            float sha = 1.0-smoothstep(-200.0,200.0,kk); sha *= 1.5;
            
            vec3 nor = normalize(denGra.yzw);
            float dif = clamp( 0.4+0.6*dot(nor,lights[0].vector), 0.0, 1.0 )*sha; 
            float fre = clamp( 1.0+dot(nor,rd), 0.0, 1.0 )*sha;
            float occ = 0.2+0.7*max(1.0-kk/200.0,0.0) + 0.1*(1.0-den);
            // lighting
            vec3 lin  = vec3(0.0);
                 lin += vec3(0.70,0.80,1.00)*1.0*(0.5+0.5*nor.y)*occ;
                 lin += vec3(0.10,0.40,0.20)*1.0*(0.5-0.5*nor.y)*occ;
                 lin += vec3(1.00,0.95,0.85)*3.0*dif*occ + 0.1;

            // color
            vec3 col = vec3(0.8,0.8,0.8)*0.45;

            col *= lin;

            //col = fog( col, t );

            // front to back blending    
            float alp = clamp(den*0.5*0.125*dt,0.0,1.0);
            col.rgb *= alp;
            sum = sum + vec4(col,alp)*(1.0-sum.a);

            thickness += dt*den;
            if( lastT<0.0 ) lastT = t;            
        }
        else 
        {
            dt = abs(den)+0.2;

        }
        t += dt;
        if( sum.a>0.995 || t>tmax ) break;
    }
    
    //resT = min(resT, (150.0-ro.y)/rd.y );
    if( lastT>0.0 ) resT = min(resT,lastT);
    //if( lastT>0.0 ) resT = mix( resT, lastT, sum.w );
    
    
    sum.xyz += max(0.0,1.0-0.0125*thickness)*vec3(1.00,0.60,0.40)*0.3*pow(clamp(dot(lights[0].vector,rd),0.0,1.0),32.0);

    return clamp( sum, 0.0, 1.0 );
}



float pnoise(in vec3 o) 
{
	vec3 p = floor(o);
	vec3 fr = fract(o);
		
	float n = p.x + p.y*57.0 + p.z * 1009.0;

	float a = hash(n+  0.0);
	float b = hash(n+  1.0);
	float c = hash(n+ 57.0);
	float d = hash(n+ 58.0);
	
	float e = hash(n+  0.0 + 1009.0);
	float f = hash(n+  1.0 + 1009.0);
	float g = hash(n+ 57.0 + 1009.0);
	float h = hash(n+ 58.0 + 1009.0);
	
	
	vec3 fr2 = fr * fr;
	vec3 fr3 = fr2 * fr;
	
	vec3 t = 3.0 * fr2 - 2.0 * fr3;
	
	float u = t.x;
	float v = t.y;
	float w = t.z;

	// this last bit should be refactored to the same form as the rest :)
	float res1 = a + (b-a)*u +(c-a)*v + (a-b+d-c)*u*v;
	float res2 = e + (f-e)*u +(g-e)*v + (e-f+h-g)*u*v;
	
	float res = res1 * (1.0- w) + res2 * (w);
	
	return res;
}

const mat3 m = mat3( 0.00,  0.80,  0.60,
                    -0.80,  0.36, -0.48,
                    -0.60, -0.48,  0.64 );

float SmoothNoise( vec3 p )
{
    float f;
    f  = 0.5000*pnoise( p ); p = m*p*2.02;
    f += 0.2500*pnoise( p ); 
	
    return f * (1.0 / (0.5000 + 0.2500));
}

vec3 getStars(in vec3 from, in vec3 dir, int levels, float power) 
{
	vec3 color=vec3(0.0);
	vec3 st = (dir * 2.+ vec3(0.3,2.5,1.25)) * .3;
	for (int i = 0; i < levels; i++) st = abs(st) / dot(st,st) - .9;
    float star = min( 1., pow( min( 5., length(st) ), 3. ) * .0025 )*1.5;

   	vec3 randc = vec3(SmoothNoise( dir.xyz*10.0*float(levels) ), SmoothNoise( dir.xzy*10.0*float(levels) ), SmoothNoise( dir.yzx*10.0*float(levels) ));
	color += star * randc;

	return pow(color*2.25, vec3(power));
}

float earthRadius = 6360e3;      // In the paper this is usually Rg or Re (radius ground, eart) 
float atmosphereRadius = 6420e3; // In the paper this is usually R or Ra (radius atmosphere) 
float Hr = 7994.f;               // Thickness of the atmosphere if density was uniform (Hr) 
float Hm = 1200.f;               // Same as above but for Mie scattering (Hm)
vec3 betaR = vec3(3.8e-6f, 13.5e-6f, 33.1e-6f); 
vec3 betaM = vec3(21e-6f); 
const float gamma = 2.2f;

vec3 position = vec3(0.f);
bool raySphereIntersect(const in vec3 rayOrigin, const in vec3 rayDirection, const in float radius, inout float t0, inout float t1) {
	vec3 L = position - rayOrigin;
	float tca = dot(L, rayDirection);

	float s2 = (dot(L, L)) - (tca * tca);

	if (s2 > radius * radius) return false;	

	float thc = sqrt((radius * radius) - s2);
	t0 = tca - thc; 
    t1 = tca + thc;

	if (t0 > t1) {
		float t = t0;
		t0 = t1;
		t1 = t;
	}

	return true;
}

vec3 computeIncidentLight(const in vec3 orig, const in vec3 dir, out float mixer) 
{ 
    uint numSamples = 16; 
    uint numSamplesLight = 8; 
    float t0 = 0.f, t1 = 0.f; 
    float g = 0.78f; 
	vec3 sunDirection = lights[0].vector;
	float tmin = 0.f, tmax = kInfinity;
    if (!raySphereIntersect(orig, dir, atmosphereRadius, t0, t1) || t1 < 0) return vec3(0.f); 
    if (t0 > tmin && t0 > 0) tmin = t0; 
    if (t1 < tmax) tmax = t1; 
    float segmentLength = (tmax - tmin) / numSamples; 
    float tCurrent = tmin; 
    vec3 sumR = vec3(0.f), sumM = vec3(0.f); // mie and rayleigh contribution 
    float opticalDepthR = 0.f, opticalDepthM = 0.f; 
    float mu = dot(dir, sunDirection); // mu in the paper which is the cosine of the angle between the sun direction and the ray direction 
    float phaseR = 3.f / (16.f * PI) * (1 + mu * mu); 
    float phaseM = 3.f / (8.f * PI) * ((1.f - g * g) * (1.f + mu * mu)) / ((2.f + g * g) * pow(1.f + g * g - 2.f * g * mu, 1.5f)); 
    for (uint i = 0; i < numSamples; ++i) { 
        vec3 samplePosition = orig + (tCurrent + segmentLength * 0.5f) * dir; 
        float height = length(samplePosition) - earthRadius; 
        // compute optical depth for light
        float hr = exp(-height / Hr) * segmentLength; 
        float hm = exp(-height / Hm) * segmentLength; 
        opticalDepthR += hr; 
        opticalDepthM += hm; 
        // light optical depth
        float t0Light = 0.f, t1Light = 0.f; 
        raySphereIntersect(samplePosition, sunDirection, atmosphereRadius, t0Light, t1Light); 
        float segmentLengthLight = t1Light / numSamplesLight, tCurrentLight = 0; 
        float opticalDepthLightR = 0.f, opticalDepthLightM = 0.f; 
        uint j = 0; 
        for (; j < numSamplesLight; ++j) { 
            vec3 samplePositionLight = samplePosition + (tCurrentLight + segmentLengthLight * 0.5f) * sunDirection; 
            float heightLight = length(samplePositionLight) - earthRadius; 
            if (heightLight < 0) break; 
            opticalDepthLightR += exp(-heightLight / Hr) * segmentLengthLight; 
            opticalDepthLightM += exp(-heightLight / Hm) * segmentLengthLight; 
            tCurrentLight += segmentLengthLight; 
        } 
        if (j == numSamplesLight) { 
            vec3 tau = betaR * (opticalDepthR + opticalDepthLightR) + betaM * 1.1f * (opticalDepthM + opticalDepthLightM); 
            vec3 attenuation = vec3(exp(-tau)); 
            sumR += attenuation * hr; 
            sumM += attenuation * hm; 
        } 
        tCurrent += segmentLength; 
    } 
	mixer = phaseR;
    return (sumR * betaR * phaseR + sumM * betaM * phaseM) * 20.f;
}
/*sky end*/

vec3 ambientColor = vec3(0.03f);

vec3 rayTrace(inout vec3 refRayOrigin, inout vec3 refRayDirection, inout vec4 ref) {
	vec3 color = vec3(0.f);
	uint shapeHit = 0;
	vec2 uv;
	float t = RayMarch(refRayOrigin, refRayDirection, shapeHit);
	//vec2 texCoord[3];

	//for (uint i = 0; i < IndexCount; i += 3) {
	//	vec3 intInfo = Intersection(refRayOrigin, refRayDirection, i);
//
	//	if (intInfo.x > 0.f && intInfo.x < minT) {			
	//		minT = intInfo.x;
	//		uv = intInfo.yz;
	//		shapeHit = i;
	//		triangleFound = true;
//
	//		//texCoord[2] = vertices[indices[i]].texCoord;
	//		//texCoord[0] = vertices[indices[i + 1]].texCoord;
	//		//texCoord[1] = vertices[indices[i + 2]].texCoord;
	//	}
	//}

    

	if (t < kInfinity) {
		vec3 p0 = refRayOrigin + t * refRayDirection;

		//vec3 uvw = vec3(uv, 1.f - uv.x - uv.y);
		//vec2 texCoords = rtLerp(uvw, texCoord[0], texCoord[1], texCoord[2]);

		vec4 materialInfo = vec4(0.f, 1.f, 1.f, 1.f);//texture(u_MaterialInfo, texCoords);
		vec3 albedo = vec3(1.f);//texture(u_Albedo, texCoords).rgb;
		float ao = materialInfo.r;
		float roughness = materialInfo.g;
		float metallic = materialInfo.b;

		// Get the normal vector
		vec3 N = GetNormal(p0);

		if (dot(refRayDirection, N) > 0.f) N = -N;

		float NdotV = max(dot(N, -refRayDirection), 0.f);
		float GSNVRoughness = GeometrySchlickGGX(NdotV, roughness);

		// calculate reflectance at normal incidence; if dia-electric (like plastic) use F0
		// of 0.04 and if it's a metal, use the albedo color as F0 (metallic workflow)
		vec3 F0 = mix(vec3(0.04f), albedo, metallic);

		const float c = 1.f / 255.f;
		// reflectance equation
		vec3 Lo = vec3(0.f);
		for (uint i = 0; i < numLights; i++)
		{
			// calculate per-light radiance
			vec3 radiance;
			uint color = lights[i].color;
			radiance.r = float((color & uint(0x000000ff))) * c;
			radiance.g = float((color & uint(0x0000ff00)) >> 8) * c;
			radiance.b = float((color & uint(0x00ff0000)) >> 16) * c;
			float radius = float((color & uint(0xff000000)) >> 24) * c;

			vec3 L = lights[i].vector;
			if (radius > 0.f){
				L -= p0;
				radiance /= dot(L, L) * radius; // radiance / attenuation
			}
			L = normalize(L);

			vec3 H = normalize(L - refRayDirection);	

            uint nu = 0;
            float d = RayMarch(p0 + N * SURF_DIST * 2.f, L, nu);
            if(d*d>=dot(L, vec3(1.f))){
				float NdotL = max(dot(N, L), 0.f);
				// Cook-Torrance BRDF
				//float NDF = DistributionGGX(N, H, roughness);
				float G = GSNVRoughness * GeometrySchlickGGX(NdotL, roughness) * DistributionGGX(N, H, roughness);
				// fresnelSchlick
				vec3 F = fresnelSchlick(max(dot(H, -refRayDirection), 0.f), F0);

				vec3 numerator = G * F;
				float denominator = 4.f * NdotV * NdotL + 0.001f; // 0.001 to prevent divide by zero.
				vec3 specular = numerator / denominator;

				vec3 kD = (1.f - F) * (1.f - metallic); // diffuse
				Lo += ((kD * albedo / PI + specular) * radiance * NdotL);  // note that we already multiplied the BRDF by the Fresnel (kS) so we won't multiply by kS again
			}
		}

		// ambient lighting (note that the next IBL tutorial will replace
		// this ambient lighting with environment lighting).

		vec3 ambient = ambientColor * ao * albedo;

		color = ambient + Lo;
		ref = vec4(albedo, fresnelSchlickRoughness(NdotV, F0, roughness));
		refRayOrigin = p0 + 0.000003 * N;
		refRayDirection = reflect(refRayDirection, N);
	}
	else{
		vec3 color1 = clamp(getStars(refRayOrigin, refRayDirection, 1, 0.5) * 1.5, 0.0, 1.0) * vec3(0.0, 0.0, 1.0);
		vec3 color2 = clamp(getStars(refRayOrigin, -refRayDirection, 2, 0.5) * 0.9, 0.0, 1.0) * vec3(1.0, 0.0, 0.0);
		vec3 color3 = clamp(getStars(refRayOrigin, -refRayDirection, 3, 0.5) * 0.7, 0.0, 1.0) * vec3(1.0, 1.0, 0.0);
		
		vec3 colorStars = getStars(refRayOrigin, refRayDirection, 17, 0.9);
		float mixer = 0.f;
		vec3 daySky = computeIncidentLight(vec3(refRayOrigin.x, earthRadius + 1.f, refRayOrigin.z), refRayDirection, mixer);
		vec3 nightSky = color1 + color2 + color3 + colorStars;
		color = mix(daySky, nightSky, mixer);

		//float resT = 2000.0;
		//vec4 res = renderClouds( refRayOrigin, refRayDirection, 0.0, resT, resT, gl_FragCoord.xy );
    	//color = color*(1.0-res.w) + res.xyz;
	}

    return color;
}

vec3 Render(const in vec3 rayDirection){
	vec3 refRayOrigin = cameraPos;
	vec3 refRayDirection = rayDirection;
	vec3 color = vec3(0.f), fil = vec3(1.f);//
	vec4 ref = vec4(0.f);

	for (uint i = 0; i < maxBounces; i++){
		vec3 pass = rayTrace(refRayOrigin, refRayDirection, ref); 
		color += pass * fil;

		fil *= ref.rgb * ref.a;
	}

	return color;
}

void main()
{
    ivec2 invocID = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = invocID / vec2(imageSize(o_Image));
    vec3 rayDir = normalize(lower_left_corner + uv.x * horizontal - uv.y * vertical - cameraPos);
	vec3 result = Render(rayDir);
	
	// HDR tonemapping
	//result = result / (result + 1.f);
	// gamma correct
	//result = pow(result, vec3(1.f / gamma));

    imageStore(o_Image, invocID, vec4(result, 1.f));
}