#pragma shader_stage(compute)

layout(local_size_x = 4, local_size_y = 4) in;
layout(binding = 0, rgba32f) restrict writeonly uniform image2D o_Image;


#include "include/Light.glsl"
#include "include/Geometry.glsl"
#include "include/Utils.glsl"

layout (std140, binding = 0) uniform SceneData
{
	vec3 lower_left_corner;
	vec3 horizontal;
	vec3 vertical;
	vec3 cameraPos;
    uint numLights;
};

layout(binding = 1) uniform sampler2D u_Albedo;

vec3 rayTrace(inout vec3 refRayOrigin, inout vec3 refRayDirection) {
	vec3 color = vec3(0.f);
	uint shapeHit = 0;
	vec2 uv = vec2(0.f);
    float minT = kInfinity;

	uint j = 0;
		//if (BoxIntersect(refRayOrigin, 1.f / refRayDirection, boundingBoxes[drawCommands[j].bvhID].start.xyz, boundingBoxes[drawCommands[j].bvhID].end.xyz)) 
		{
			for (uint i = 0; i < drawCommands[j].count; i += 3) {
				vec3 intInfo = Intersection(refRayOrigin, refRayDirection, i, drawCommands[j]);

				if (intInfo.x > 0.f && intInfo.x < minT) {			
					minT = intInfo.x;
					uv = intInfo.yz;
					shapeHit = i;
				}
			}  
		}
	
	
		color = abs(refRayDirection);	
	if (minT != kInfinity) {
		vec3 uvw = vec3(uv, 1.f - uv.x - uv.y);
		vec2 texCoords = rtLerp(uvw, vec2(0.f, 1.f), vec2(1.f, 0.f), vec2(0.f, 0.f));

		color = abs(uvw);		
	}

    return color;
}

vec3 Render(const in vec3 rayDirection){
	vec3 refRayOrigin = cameraPos;
	vec3 refRayDirection = rayDirection;
	vec3 color = rayTrace(refRayOrigin, refRayDirection);

	return color;
}

void main()
{
    ivec2 invocID = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = invocID / vec2(imageSize(o_Image));
	vec3 result = Render(normalize(lower_left_corner + uv.x * horizontal - uv.y * vertical - cameraPos));

    imageStore(o_Image, invocID, vec4(result, 1.f));
}