#pragma shader_stage(compute)

layout(local_size_x = 4, local_size_y = 4) in;
layout(binding = 0, rgba32f) restrict writeonly uniform image2D o_Image;

#extension GL_EXT_shader_8bit_storage : require

#include "include/Light.glsl"
#include "include/Geometry.glsl"
#include "include/Utils.glsl"

layout (std140, binding = 0) uniform SceneData
{
	vec3 lower_left_corner;
	vec3 horizontal;
	vec3 vertical;
	vec3 cameraPos;
    uint numLights;
	uint maxBounces;
};

layout(binding = 1) uniform sampler2D u_Albedo;
layout(binding = 2) uniform sampler2D u_MaterialInfo;

/*sky start*/
float hash( const in float n ) { return fract(sin(n)*4378.5453); }

float hash1( vec2 p ) {
    p  = 50.0*fract( p*0.3183099 );
    return fract( p.x*p.y*(p.x+p.y) );
}

float hash1( float n ) { return fract(n * 17.f * fract(n * 0.3183099f)); }

float noise( in vec3 x )
{
    vec3 p = floor(x);
    vec3 w = fract(x);
    
    vec3 u = w*w*w*(w*(w*6.0-15.0)+10.0);

    float n = p.x + 317.0*p.y + 157.0*p.z;
    
    float a = hash1(n+0.0);
    float b = hash1(n+1.0);
    float c = hash1(n+317.0);
    float d = hash1(n+318.0);
    float e = hash1(n+157.0);
	float f = hash1(n+158.0);
    float g = hash1(n+474.0);
    float h = hash1(n+475.0);

    float k0 = a;
    float k1 = b - a;
    float k2 = c - a;
    float k3 = e - a;
    float k4 = a - b - c + d;
    float k5 = a - c - e + g;
    float k6 = a - b - e + f;
    float k7 = b + c - d + e - f - g + h - a;

    return -1.0+2.0*(k0 + k1*u.x + k2*u.y + k3*u.z + k4*u.x*u.y + k5*u.y*u.z + k6*u.z*u.x + k7*u.x*u.y*u.z);
}

float pnoise(in vec3 o) 
{
	vec3 p = floor(o);
	vec3 fr = fract(o);
		
	float n = p.x + p.y*57.0 + p.z * 1009.0;

	float a = hash(n+  0.0);
	float b = hash(n+  1.0);
	float c = hash(n+ 57.0);
	float d = hash(n+ 58.0);
	
	float e = hash(n+  0.0 + 1009.0);
	float f = hash(n+  1.0 + 1009.0);
	float g = hash(n+ 57.0 + 1009.0);
	float h = hash(n+ 58.0 + 1009.0);
	
	
	vec3 fr2 = fr * fr;
	vec3 fr3 = fr2 * fr;
	
	vec3 t = 3.0 * fr2 - 2.0 * fr3;
	
	float u = t.x;
	float v = t.y;
	float w = t.z;

	// this last bit should be refactored to the same form as the rest :)
	float res1 = a + (b-a)*u +(c-a)*v + (a-b+d-c)*u*v;
	float res2 = e + (f-e)*u +(g-e)*v + (e-f+h-g)*u*v;
	
	float res = res1 * (1.0- w) + res2 * (w);
	
	return res;
}

float SmoothNoise( vec3 p )
{
    float f = 0.5 * pnoise(p);
	p = m * p * 2.02;
    f += 0.25 * pnoise(p); 
	
    return f * (1.0 / (0.5000 + 0.2500));
}

vec3 getStars(in vec3 from, in vec3 dir, int levels, float power) 
{
	vec3 color=vec3(0.0);
	vec3 st = (dir * 2.+ vec3(0.3,2.5,1.25)) * .3;
	for (int i = 0; i < levels; i++) st = abs(st) / dot(st,st) - .9;
    float star = min( 1., pow( min( 5., length(st) ), 3. ) * .0025 )*1.5;

   	vec3 randc = vec3(SmoothNoise( dir.xyz*10.0*float(levels) ), SmoothNoise( dir.xzy*10.0*float(levels) ), SmoothNoise( dir.yzx*10.0*float(levels) ));
	color += star * randc;

	return pow(color*2.25, vec3(power));
}

vec3 position = vec3(0.f);
bool raySphereIntersect(const in vec3 rayOrigin, const in vec3 rayDirection, const in float radius, inout float t0, inout float t1) {
	vec3 L = position - rayOrigin;
	float tca = dot(L, rayDirection);

	float s2 = (dot(L, L)) - (tca * tca);

	if (s2 > radius * radius) return false;	

	float thc = sqrt((radius * radius) - s2);
	t0 = tca - thc; 
    t1 = tca + thc;

	if (t0 > t1) {
		float t = t0;
		t0 = t1;
		t1 = t;
	}

	return true;
}

vec3 computeIncidentLight(const in vec3 rayOrigin, const in vec3 rayDirection, out float mixer) 
{ 
    uint numSamples = 16; 
    uint numSamplesLight = 8; 
    float t0 = 0.f, t1 = 0.f; 
    float g = 0.78f; 
	vec3 sunDirection = lights[0].vector;
	float tmin = 0.f, tmax = kInfinity;
    if (!raySphereIntersect(rayOrigin, rayDirection, atmosphereRadius, t0, t1) || t1 < 0) return vec3(0.f); 
    if (t0 > tmin && t0 > 0) tmin = t0; 
    if (t1 < tmax) tmax = t1; 
    float segmentLength = (tmax - tmin) / numSamples; 
    float tCurrent = tmin; 
    vec3 sumR = vec3(0.f), sumM = vec3(0.f); // mie and rayleigh contribution 
    float opticalDepthR = 0.f, opticalDepthM = 0.f; 
    float mu = dot(rayDirection, sunDirection); // mu in the paper which is the cosine of the angle between the sun direction and the ray direction 
    float phaseR = 3.f / (16.f * PI) * (1 + mu * mu); 
    float phaseM = 3.f / (8.f * PI) * ((1.f - g * g) * (1.f + mu * mu)) / ((2.f + g * g) * pow(1.f + g * g - 2.f * g * mu, 1.5f)); 
    for (uint i = 0; i < numSamples; ++i) { 
        vec3 samplePosition = rayOrigin + (tCurrent + segmentLength * 0.5f) * rayDirection; 
        float height = length(samplePosition) - earthRadius; 
        // compute optical depth for light
        float hr = exp(-height / Hr) * segmentLength; 
        float hm = exp(-height / Hm) * segmentLength; 
        opticalDepthR += hr; 
        opticalDepthM += hm; 
        // light optical depth
        float t0Light = 0.f, t1Light = 0.f; 
        raySphereIntersect(samplePosition, sunDirection, atmosphereRadius, t0Light, t1Light); 
        float segmentLengthLight = t1Light / numSamplesLight, tCurrentLight = 0; 
        float opticalDepthLightR = 0.f, opticalDepthLightM = 0.f; 
        uint j = 0; 
        for (; j < numSamplesLight; ++j) { 
            vec3 samplePositionLight = samplePosition + (tCurrentLight + segmentLengthLight * 0.5f) * sunDirection; 
            float heightLight = length(samplePositionLight) - earthRadius; 
            if (heightLight < 0) break; 
            opticalDepthLightR += exp(-heightLight / Hr) * segmentLengthLight; 
            opticalDepthLightM += exp(-heightLight / Hm) * segmentLengthLight; 
            tCurrentLight += segmentLengthLight; 
        } 
        if (j == numSamplesLight) { 
            vec3 tau = betaR * (opticalDepthR + opticalDepthLightR) + betaM * 1.1f * (opticalDepthM + opticalDepthLightM); 
            vec3 attenuation = vec3(exp(-tau)); 
            sumR += attenuation * hr; 
            sumM += attenuation * hm; 
        } 
        tCurrent += segmentLength; 
    } 
	mixer = phaseR;
    return (sumR * betaR * phaseR + sumM * betaM * phaseM) * 20.f;
}
/*sky end*/

vec3 ambientColor = vec3(0.03f);

vec3 rayTrace(inout vec3 refRayOrigin, inout vec3 refRayDirection) {
	vec3 color = vec3(0.f);
	uint shapeHit = 0;
	vec2 uv = vec2(0.f);
    float minT = kInfinity;

	for (uint j = 0; j < drawCommands.length(); j++) {
		if (BoxIntersect(refRayOrigin, 1.f / refRayDirection, 
		boundingBoxes[drawCommands[j].bvhID].start.xyz, boundingBoxes[drawCommands[j].bvhID].end.xyz)) {
			for (uint i = drawCommands[j].firstIndex; i < drawCommands[j].firstIndex + drawCommands[j].count; i += 3) {
				vec3 intInfo = Intersection(refRayOrigin, refRayDirection, i, drawCommands[j]);

				if (intInfo.x > 0.f && intInfo.x < minT) {			
					minT = intInfo.x;
					uv = intInfo.yz;
					shapeHit = i;
				}
			}  
		}
	}

	if (minT != kInfinity) {
		vec3 p0 = refRayOrigin + minT * refRayDirection;

		vec3 uvw = vec3(uv, 1.f - uv.x - uv.y);
		vec2 texCoords = rtLerp(uvw, vertices[indices[shapeHit + 1]].texCoord, vertices[indices[shapeHit + 2]].texCoord, vertices[indices[shapeHit]].texCoord);

		vec4 materialInfo = texture(u_MaterialInfo, texCoords);
		vec3 albedo = texture(u_Albedo, texCoords).rgb;

		float emissive = materialInfo.r;
		if (emissive > 0.f) return vec3(emissive) * albedo + albedo;

		float perceptualRoughness = materialInfo.g;
		float metallic = materialInfo.b;
		float ao = 1.f;

		// Get the normal vector
        vec3 aPos = vertices[indices[shapeHit]].position;

    	vec3 v1v0 = vertices[indices[shapeHit + 1]].position - aPos;
    	vec3 v2v0 = vertices[indices[shapeHit + 2]].position - aPos;
		vec3 N = normalize(cross( v1v0, v2v0 ));

		if (dot(refRayDirection, N) > 0.f) N = -N;

		float NoV = max(dot(N, -refRayDirection), 0.f);

		float roughness = materialInfo.g;
		float roughnessSqrd = roughness * roughness;
		float roughness1 = roughness + 1.f;
		float k1 = roughness1 * roughness1 * 0.125f;
		float smoothness = 1.f - roughness;
		float GSNVRoughness = GeometrySchlickGGX(NoV, k1);

		// calculate reflectance at normal incidence; if dia-electric (like plastic) use F0
		// of 0.04 and if it's a metal, use the albedo color as F0 (metallic workflow)
		vec3 F0 = mix(vec3(0.04f), albedo, metallic);

		const float c = 1.f / 255.f;
		// reflectance equation
		vec3 Lo = vec3(0.f);
		for (uint i = 0; i < numLights; i++)
		{
			// calculate per-light radiance
			vec3 radiance;
			uint color = lights[i].color;
			radiance.r = float((color & uint(0x000000ff))) * c;
			radiance.g = float((color & uint(0x0000ff00)) >> 8) * c;
			radiance.b = float((color & uint(0x00ff0000)) >> 16) * c;
			float radius = float((color & uint(0xff000000)) >> 24) * c;

			vec3 L = lights[i].vector;
			if (radius > 0.f){
				L -= p0;
				radiance /= dot(L, L) * radius; // radiance / attenuation
			}
			L = normalize(L);

            bool bShadow = false;
			if (radius > 0.f) {
				//for (uint j = 0; j < drawCommands.length(); j++) {
				//	if (bShadow) break;
				//	if (BoxIntersect(refRayOrigin, 1.f / refRayDirection, 
				//	boundingBoxes[drawCommands[j].bvhID].start.xyz, boundingBoxes[drawCommands[j].bvhID].end.xyz))
				//	for (uint i = drawCommands[j].firstIndex; i < drawCommands[j].firstIndex + drawCommands[j].count; i += 3) {
				//		vec3 intInfo = Intersection(p0 + 0.000001 * N, L, i);
				//		if (intInfo.x > 0.f){
				//			bShadow = true;
				//		}
				//	}	
				//}
			}
            
			vec3 H = normalize(L - refRayDirection);

			float NoL = max(dot(N, L), 0.f);
			float NoH = max(dot(N, H), 0.f);
			// Cook-Torrance BRDF
			float G = GSNVRoughness * GeometrySchlickGGX(NoL, k1) * DistributionGGX(NoH, roughnessSqrd);
			// fresnelSchlick
			vec3 F = fresnelSchlick(max(dot(H, -refRayDirection), 0.f), F0);

			vec3 numerator = G * F;
			float denominator = 4.f * NoV * NoL + 0.001f; // 0.001 to prevent divide by zero.
			vec3 specular = numerator / denominator;

			vec3 kD = (1.f - F) * (1.f - metallic); // diffuse
			Lo += ((kD * albedo / PI + specular) * radiance * NoL) * float(!bShadow);  // note that we already multiplied the BRDF by the Fresnel (kS) so we won't multiply by kS again			
		}

		// ambient lighting (note that the next IBL tutorial will replace
		// this ambient lighting with environment lighting).

		color = ambientColor * albedo + Lo;

		refRayOrigin = p0 + 0.000003 * N;
		refRayDirection = reflect(refRayDirection, N);
	}
	else{
		vec3 color1 = clamp(getStars(refRayOrigin, refRayDirection, 1, 0.5) * 1.5, 0.0, 1.0) * vec3(0.0, 0.0, 1.0);
		vec3 color2 = clamp(getStars(refRayOrigin, -refRayDirection, 2, 0.5) * 0.9, 0.0, 1.0) * vec3(1.0, 0.0, 0.0);
		vec3 color3 = clamp(getStars(refRayOrigin, -refRayDirection, 3, 0.5) * 0.7, 0.0, 1.0) * vec3(1.0, 1.0, 0.0);
		
		vec3 colorStars = getStars(refRayOrigin, refRayDirection, 17, 0.9);
		float mixer = 0.f;
		vec3 daySky = computeIncidentLight(vec3(refRayOrigin.x, earthRadius + 1.f, refRayOrigin.z), refRayDirection, mixer);
		vec3 nightSky = color1 + color2 + color3 + colorStars;
		color = mix(daySky, nightSky, mixer);
		color = vec3(1.f);

		//float resT = 2000.0;
		//vec4 res = renderClouds( refRayOrigin, refRayDirection, 0.0, resT, resT, gl_FragCoord.xy );
    	//color = color*(1.0-res.w) + res.xyz;
	}

    return color;
}

float dot2( in vec3 v ) { return dot(v,v); }

float udTriangle(vec3 p, vec3 a, vec3 b, vec3 c )
{
  vec3 ba = b - a; vec3 pa = p - a;
  vec3 cb = c - b; vec3 pb = p - b;
  vec3 ac = a - c; vec3 pc = p - c;
  vec3 nor = cross( ba, ac );

  return sqrt(
    (sign(dot(cross(ba,nor),pa)) +
     sign(dot(cross(cb,nor),pb)) +
     sign(dot(cross(ac,nor),pc))<2.0)
     ?
     min( min(
     dot2(ba*clamp(dot(ba,pa)/dot2(ba),0.0,1.0)-pa),
     dot2(cb*clamp(dot(cb,pb)/dot2(cb),0.0,1.0)-pb) ),
     dot2(ac*clamp(dot(ac,pc)/dot2(ac),0.0,1.0)-pc) )
     :
     dot(nor,pa)*dot(nor,pa)/dot2(nor) );
}

float GetDist(vec3 p) {
    float minT = kInfinity;

	for (uint j = 0; j < drawCommands.length(); j++) {
		for (uint i = drawCommands[j].firstIndex; i < drawCommands[j].firstIndex + drawCommands[j].count; i += 3) {
			vec3 a = vertices[indices[i]].position;
			vec3 b = vertices[indices[i + 1]].position;
			vec3 c = vertices[indices[i + 2]].position;
			minT = min(minT, udTriangle(p, a, b, c));
		}		
	}

    return minT;
}

float RayMarch(vec3 ro, vec3 rd) {
	float dO=0.;
    
    for(int i=0; i<MAX_STEPS; i++) {
    	vec3 p = ro + rd*dO;
        float dS = GetDist(p);
        dO += dS;
        if(dO>MAX_DIST || dS<SURF_DIST) break;
    }
    
    return dO;
}

vec3 GetNormal(vec3 p) {
	float d = GetDist(p);
    vec2 e = vec2(.01, 0);
    
    vec3 n = d - vec3(
        GetDist(p-e.xyy),
        GetDist(p-e.yxy),
        GetDist(p-e.yyx));
    
    return normalize(n);
}

float GetLight(vec3 p) {
    vec3 lightPos = vec3(0, 5, 6);
    vec3 l = normalize(lightPos-p);
    vec3 n = GetNormal(p);
    
    float dif = clamp(dot(n, l), 0., 1.);
    float d = RayMarch(p+n*SURF_DIST*2., l);
    if(d<length(lightPos-p)) dif *= .1;
    
    return dif;
}

vec3 rayMarch(inout vec3 refRayOrigin, inout vec3 refRayDirection){
	vec3 col = vec3(0);

    float t = RayMarch(refRayOrigin, refRayDirection);
    
    vec3 p = refRayOrigin + refRayDirection * t;
    
    float dif = GetLight(p);
    col = vec3(dif);
    
	return col;
}

vec3 rayTraceVoxel(inout vec3 refRayOrigin, inout vec3 refRayDirection) {

	ivec3 vMapCheck = ivec3(floor(refRayOrigin)), vStep = ivec3(0), vMapPrevious = ivec3(floor(refRayOrigin));
	vec3 vRayLength1D = vec3(0.f);
	vec3 vRayUnitStepSize = abs(1.f / refRayDirection);

	// Establish Starting Conditions
	for (int i = 0; i < 3; i++) {
		if (refRayDirection[i] < 0)
		{
			vStep[i] = -1;
			vRayLength1D[i] = (refRayOrigin[i] - float(vMapCheck[i])) * vRayUnitStepSize[i];
		}
		else
		{
			vStep[i] = 1;
			vRayLength1D[i] = (float(vMapCheck[i] + 1) - refRayOrigin[i]) * vRayUnitStepSize[i];
		}
	}

	vec3 color = vec3(1.f);
	float fDistance = 0.f;
	while (fDistance < fMaxDistance)
	{
		// Test tile at new test point
		if (vMapCheck.x < chunkSize && vMapCheck.x >= 0 && 
		    vMapCheck.y < chunkSize && vMapCheck.y >= 0 && 
			vMapCheck.z < chunkSize && vMapCheck.z >= 0) {
			uint blockID = getBlock(vMapCheck);
			if (blockID > 0)
			{
				vec3 N = vec3(vMapPrevious - vMapCheck); 
				color = vec3(0.f, 1.f, 0.f) * dot(N, lights[0].vector.xyz);
				break;
			}
		}

		vMapPrevious = vMapCheck;
		// Walk along shortest path
		int axis = 0;
		for (int i = 0; i < 3; i++) {
			int nextAxis = (i + 1) % 3;
			if (vRayLength1D[axis] > vRayLength1D[nextAxis]) axis = nextAxis;
		}

		vMapCheck[axis] += vStep[axis];
		fDistance = vRayLength1D[axis];
		vRayLength1D[axis] += vRayUnitStepSize[axis];		
	}


	return color;
}

vec3 Render(const in vec3 rayDirection){
	vec3 refRayOrigin = cameraPos;
	vec3 refRayDirection = rayDirection;
	vec3 color = rayTraceVoxel(refRayOrigin, refRayDirection);

	return color;
}

void main()
{
    ivec2 invocID = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = invocID / vec2(imageSize(o_Image));
	vec3 result = Render(normalize(lower_left_corner + uv.x * horizontal - uv.y * vertical - cameraPos));

    imageStore(o_Image, invocID, vec4(result, 1.f));
}